name: soundbuilder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.2.3
  shared_preferences: ^2.5.3
  audio_engine:
    path: ../audio_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.3.3
  rename: ^3.1.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds.json
    - assets/sounds/
